[server]
headless = true
port = 8501

[theme]
primaryColor = "#D33682"
backgroundColor = "#E6AE81"
secondaryBackgroundColor = "#586E75"
textColor = "#FDF6E3"
font = "sans serif"

[markdown]
linkColor = "#268BD2"
